### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by ehen2432** [SirFluffDev/nameless-sky#1]
when i open the html5 file in a browser, it shows the loading screen and does nothing else. how do i play?

**Comment by SirFluffDev** [comment]
You have to host it on a local web server, or just play it [here](https://sirfluffdev.github.io/nameless-sky/)

**Comment by SirFluffDev** [comment]
Also, if I may be so inclined - how did you manage to come across this project? You're the first other person I've seen on the project page.
